Pandas Basics

In [ ]:
# Pandas Series
import pandas as pd
from pandas.core.reshape.concat import validate_unique_levels

s1 = pd.Series([1, 2, 3, 4, 5])
print(s1)
print("-----------")
s2 = pd.Series([11,12,13,14,5], name="sl.no", index=['a','b','c','d','e'])
print(type(s2))
s2.index

In [ ]:
## Defining the data as dictionary values.
## City will be first column and second column will be Population with values in the square brackets.
## by default index 0,1... will be assigned.

data = {
    'City':['San Francisco', 'San Jose', 'Seattle'],
    'Population':[100000, 20000, 30000]
}

## Default dataframe creation without any other optional parameters
# df2 = pd.DataFrame(data)

## You can provide custom indexes while creating the data frame
# df = pd.DataFrame(data, index=['Case 1', 'Case 2', 'Case 3'])

## you can rename the column names when dataframe is created
##df = pd.DataFrame(data, columns=['City1','Population2'])

## you can give index, new column names all in one method while creating dataframe.
df = pd.DataFrame(data, index=['Case 1', 'Case 2', 'Case 3'], columns=['City3','Population3'])

# df2 = pd.DataFrame(data)
print(df)
df.index

In [ ]:
## Creating  dataframes using from_dict function with orientation options
data_dict = {
    'City':['New York', 'New Delhi', 'New Jersey'],
    'Population':[100000, 2000000, 30000]
}

## Default
df_default = pd.DataFrame.from_dict(data_dict)

# ## Orient by columns
# df_columns = pd.DataFrame.from_dict(data_dict, orient='columns')
#
# ## Orient by index
# df_index = pd.DataFrame.from_dict(data_dict, orient='index')

print("------default----------")
print(df_default)
print()

print("------orient=columns----------")
print(df_columns)

print()
print("------orient=index----------")
print(df_index)

In [ ]:
## Creating dataframes from List of dictionaries
list_dict = [
    {'City': 'New York', 'Population': 100000},
    {'City': 'New Delhi', 'Population': 900000},
    {'City': 'New Jersey', 'Population': 700000},
]

df_list_dict = pd.DataFrame(list_dict)

df_list_dict

In [ ]:
## Creating dataframes from a tuples
## No need to define/repeat the column names as above
data_tuples = [
    ('San Francisco', 990099),
    ('San Jose', 788899),
    ('Seattle', 567822)
]

df_tuples = pd.DataFrame.from_records(data_tuples, columns=['City', 'Population'])

df_tuples

In [ ]:
## Creating dataframes from array of strings (list & zip functions - bundling the data using the zip function)
cities = ['San Francisco','San Jose','Seattle']
populations = [1023113,121511,313111]

#bundling the two arrays
data_zip = list(zip(cities,populations))

## creating the dataframe using the bundled/zipped data
df_zip = pd.DataFrame(data_zip, columns=['City','Population'])

df_zip

In [ ]:
## Using series to prepare the data and concatenate it. Concatenating the Series to create dataframe
city_series = pd.Series(['San Francisco','San Jose','Seattle'],name='City')
population_series = pd.Series([100000,90000,150000], name='Population')

# df = pd.concat([city_series,population_series],axis=1) #axis=1, horizontal concatenation
df = pd.concat([city_series,population_series], axis=1) #axis=1, horizontal concatenation

df

Filtering with loc and iloc

In [ ]:
#Create a dataframe
customer_data = {
    'Name': ['Lily','Emma', 'John'],
    'Age': [38, 35, 28],
    'Education': ['high school', 'phd', 'bachelor of science'],
    'Gender': ['F', 'F', 'M']
}
# customer = pd.DataFrame(data, index=['a','b','c'])
customer = pd.DataFrame(customer_data)
# customer
# customer.reset_index(drop=True)

## using loc - loc uses labels. slicing in loc, the last element is inclusive. that 0:1 results in 0 and 1st position.
''' This is not working, it is showing the columns beyond Education - don't know why?'''
# customer.loc[0:1,'Name':'Education']
# customer

''' this works'''
print(customer.loc[0:1,'Name':'Education'])

## using iloc - iloc uses indexes. here slicing the last element is not inclusive. check the difference in both these examples

''' This is also not working, it is showing the columns beyond Education - don't know why?'''
# customer.iloc[[0,2],[0,1]]
# customer

'''this works'''
print(customer.iloc[[0,2],[0,1,2]])

print("----")
print(customer.iloc[0:2,[0,1,3]]) # same without print doesn't work - not sure

'''this doesn't works'''
# print(customer.iloc[0:2,[0:3]])

Column Access & Filter conditions - Dataframes

In [ ]:
cus_ed = customer.Education
## Avoid spaces in the column names as the above method of column access doesn't work

## alternative
cus_ed = customer['Education'] ## this gives you a pandas Series

## if you want to get the column in as a dataframe, give double []
type(customer[['Age','Education']])

condition = customer['Age'] > 28
print(customer[condition])
print("----")

condition = (customer['Gender'] == 'F') & (customer['Education'] == 'phd')
print(customer[condition])
print("----")

## filtering using reg expression
condition = customer['Name'].str.contains(r'^[E]', regex=True)
customer_filtered = customer[condition]
print(customer_filtered)

Handling Missing Values

In [ ]:

import numpy as np
student_data = {
    'account_length': [20,20,np.nan, 20,30],
    'gender': [np.nan, 'M', 'M', 'F', 'F'],
    'education': ['high school', 'high school', 'high school', 'high school', np.nan]
}
df = pd.DataFrame(student_data, index=['a','b','c','d','e'])
df.reset_index()

#Replace the missing value with average value of the column 'account_length'
value_to_replace = df['account_length'].mean()
# print(value_to_replace)

# - this action will not affect the original dataframe. only on the copy of the dataframe.
# df['account_length'].fillna(value_to_replace)

# - this action will not affect the original dataframe. only on the copy of the dataframe.
# df['account_length'].fillna(value_to_replace, inplace=True)

## This is the better way of doing the fillna. direct method on the dataframe
# df.fillna({'account_length': value_to_replace}, inplace=True)
# df.fillna({'gender':'M'}, inplace=True)

## Mode 0 is required to get the value as mode() returns a pd.Series
mode_value = df['education'].mode()[0]

# print(type(mode_value))
# df.fillna({'education':mode_value}, inplace=True)

# Submitting the fillna in one statement for all columns
df.fillna(
    {
        'account_length': value_to_replace,
        'education': mode_value,
        'gender': 'F'
    }, inplace=True
)

Sorting in a dataframe

In [ ]:
product_data = {
    'Date': ['2023-09-01','2023-09-02','2023-09-03','2023-09-04'],
    'Product': ['Product A','Product B','Product A','Product C'],
    'Quantity Sold': [100, 150, 120, 80],
    'Revenue': [5000,7500,6000,4000]
}
df = pd.DataFrame(product_data)
# df.sort_values(by='Revenue', ascending=False)

#reset_index preserves the old and new index
df.sort_values(by='Revenue', ascending=False).reset_index()

#drop the old index and retains the new index after the sorting
df.sort_values(by='Revenue', ascending=False).reset_index(drop=True)

In [ ]:
student_score_data = {
    'Student_Name': ['Alice', 'Bob', 'Eve', 'David', 'Carol'],
    'Age': [25,30,22,24,28],
    'Score': [95,93,95,88,88]
}
df = pd.DataFrame(student_score_data)
df.sort_values(by='Score', ascending = False).reset_index(drop=True)

# Multiple Sort- Sort score from highest to the lowest, sort the student age from the smallest to the largest
df.sort_values(by=['Score','Age'], ascending=[False, True]).reset_index(drop=True)

DATA ANALYSIS WITH PANDAS

In [184]:
product_data1 = {
    'product_category': ['baby','book','book','beauty','baby'],
    'product_price': [19.99, 12.49, 22, 49, 16],
    'rating': [5,3,3,2,4]
}
df = pd.DataFrame(product_data1)
df

  product_category  product_price  rating
0             baby          19.99       5
1             book          12.49       3
2             book          22.00       3
3           beauty          49.00       2
4             baby          16.00       4

In [198]:
#What is the average rating by product category?

avg_rating_summary = df.groupby('product_category')['rating'].mean().reset_index()

## renaming the rating column name to avg_rating
avg_rating_summary.rename(columns={'rating':'avg_rating'}, inplace=True)
avg_rating_summary

  product_category  avg_rating
0             baby         4.5
1           beauty         2.0
2             book         3.0

In [230]:
## What is the average product price and total quantity of each product category
product_price_qty = {
    'order_id': ['4235','2342','1234','5325','1342'],
    'product_category': ['baby','beauty', 'baby','beauty', 'beauty'],
    'product': ['diaper','eye liner', 'diaper','eye shadow', 'face mask'],
    'product_price': [19.99, 12.49, 22, 49, 16],
    'quantity': [5,3,3,2,4]
}

df = pd.DataFrame(product_price_qty)

## this gives only the average product price. we need the total qty as well..
avg_product_price_total_qty = df.groupby('product_category')['product_price'].mean().reset_index()
# avg_product_price_total_qty

## for multiple criterias then use agg() function
avg_product_price_total_qty = df.groupby('product_category').agg({'product_price':'mean', 'quantity':'sum'}).reset_index()
print(df)

avg_product_price_total_qty.rename(columns={'product_price':'avg_product_price', 'quantity':'total_qty'}, inplace=True)
avg_product_price_total_qty

  order_id product_category     product  product_price  quantity
0     4235             baby      diaper          19.99         5
1     2342           beauty   eye liner          12.49         3
2     1234             baby      diaper          22.00         3
3     5325           beauty  eye shadow          49.00         2
4     1342           beauty   face mask          16.00         4

  product_category  avg_product_price  total_qty
0             baby             20.995          8
1           beauty             25.830          9

Concatenate dataframes

In [232]:
csv_url='https://raw.githubusercontent.com/agconti/kaggle-titanic/master/daa/train.csv'
with open(csv_url,'r') as file:
    content = file.read()
    print(content)

OSError: [Errno 22] Invalid argument: 'https://raw.githubusercontent.com/agconti/kaggle-titanic/master/daa/train.csv'